project_id = "bskfnthwewhpfrldbhqx"

[functions.global-search]
verify_jwt = false

[functions.vault-ingest]
verify_jwt = false

[functions.create-api-key]
verify_jwt = false

[functions.revoke-api-key]
verify_jwt = false

[functions.vault-crud]
verify_jwt = false

[functions.projects-crud]
verify_jwt = false

[functions.folders-crud]
verify_jwt = false

[functions.project-api-keys-crud]
verify_jwt = false

[functions.bugs-crud]
verify_jwt = false

[functions.dashboard-stats]
verify_jwt = false

[functions.list-devvault-keys]
verify_jwt = false

[functions.profiles-crud]
verify_jwt = false

[functions.vault-query]
verify_jwt = false
